import Head from "next/head";
import { Wrapper } from "@/components/styled";

export default function Home() {
  return (
    <>
      <Head>
        <title>Museum App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Wrapper></Wrapper>
      </main>
    </>
  );
}
